const asset = (path: string) => `${import.meta.env.BASE_URL}/${path}`

export const iconSet = {
  AntDesign: asset('svgs/AntDesign.svg'),
  Astro: asset('svgs/Astro.svg'),
  Axios: asset('svgs/Axios.svg'),
  Element: asset('svgs/Element.svg'),
  NextJS: asset('svgs/NextJS.svg'),
  NodeJS: asset('svgs/NodeJS.svg'),
  React: asset('svgs/React.svg'),
  ReactRouter: asset('svgs/ReactRouter.svg'),
  Redux: asset('svgs/Redux.svg'),
  Sass: asset('svgs/Sass.svg'),
  SocketIO: asset('svgs/SocketIO.svg'),
  Solid: asset('svgs/Solid.svg'),
  TRPC: asset('svgs/TRPC.svg'),
  TypeScript: asset('svgs/TypeScript.svg'),
  UnoCSS: asset('svgs/UnoCSS.svg'),
  Vite: asset('svgs/Vite.svg'),
  Vue: asset('svgs/Vue.svg'),
  PostSQL: asset('svgs/PostSQL.svg'),
  T3: asset('svgs/T3.svg'),
  Zod: asset('svgs/Zod.svg'),
  TailwindCSS: asset('svgs/TailwindCSS.svg'),
  PostgreSQL: asset('svgs/PostgreSQL.svg'),
  JavaScript: asset('svgs/JavaScript.svg'),
  'Next.js': asset('svgs/Next.js.svg'),
  'Node.js': asset('svgs/Node.js.svg'),
  ShadcnUI: asset('svgs/ShadcnUI.svg'),
  Prisma: asset('svgs/Prisma.svg'),
}
